### ISSUE TITLE
Unable to use parjs

### ISSUE THREAD

**Issue by lu4** [GregRos/parjs#22]
I've tried launching basic example from docs, however my typescript environment is unable to locate parjs module after installation. I've attached basic example, just unzip and run `npm i` to install it's dependencies. After that any attempt to compile the project using command-line `tsc` call gives 
![image](https://user-images.githubusercontent.com/1069295/69020136-35d6e980-09bc-11ea-8869-f076398bc61b.png)

Here is basic example zip file:
[parjs-example.zip](https://github.com/GregRos/parjs/files/3856556/parjs-example.zip)

It looks like a bug or am I wrong?...

**Comment by PsychoLlama** [comment]
Judging by the source code, It looks like the wrong package got published 🙈

There's a script called [`publish.ts`](https://github.com/GregRos/parjs/blob/fb2740a7c43b9a5ef87b006359b741610c62f2d9/src/publish.ts) that creates a new `.tmp/publish` package with everything the documentation suggests, confirmed by the fact that it works locally if I symlink it in node_modules.

`0.12.3` seems to have published `parjs` instead of `parjs/.tmp/publish`.

In the meantime, downgrading to `0.12.2` fixes the issue.

**Comment by GregRos** [comment]
Thanks for the headsup! Yes, I think it's a 🙈 issue indeed. I uploaded a new version and it works now.
