### ISSUE TITLE
Request: a manySepBy variant that captures the separators

### ISSUE THREAD

**Issue by soul-codes** [GregRos/parjs#35]
Currently, the `manySepBy` combinator would return the things that are separated while discarding the separator. I would like to propose a variant of this combinator that returns a projection that has the separator included, perhaps satisfying this kind of interface:

```ts
interface Alternation<Term, Separator> {
    firstTerm: Term;
    subsequentTerms: SubsequentTerm<Term, Separator>[]
}

interface SubsequentTerm<Term, Separator> {
   separator: Separator;
   term: Term; // on the RHS of the separator.
}
```

**Comment by GregRos** [comment]
Thank you for the suggestion! I decided to implement it differently because returning an array matches the behavior of Parsec.

`manySepBy` will return an array that, by the power of JavaScript, will have an extra key called `separators` with another array containing the values returned by the separator parser.

```typescript
const result = string("a").pipe(manySepBy(",")).parse("a,a").value
arrWithSeps.join(" ") // "a a"
arrWithSeps.separators.join(" ") // ","
```
