### ISSUE TITLE
Hard failure when soft expected

### ISSUE THREAD

**Issue by cdaringe** [GregRos/parjs#65]
# Problem

I have an expr like:

```ts
const m = p1.pipe(maybe(), then(p2));
m.parse(onlySatisfiesP2); // Hard failure from p1, when Success expected
```

# Reproduction

- minimal demo: https://github.com/cdaringe/email-parser/blob/main/issue.ts#L56
- clone and `npm install` (or pnpm install, as i'm using)
- run the module: `node -r ts-node/register issue.ts` or `bun issue.ts` 

# Discussion

It seems in some circumstances Soft is promoted to Hard, but it's not clear when. Further, I _expected_ a soft failure above, wanted the maybe() to catch, then successfully parse using the `then(expr)`. I've tried debugging, and it's a bit wonky to debug, but I see the promotion happening in the `Then` instance if the Soft failure isn't the first failure. I'm trying to write an email parser, with many _optional, leading expressions_ in the grammar. Any tips would be welcomed. Much appreciated!

**Comment by cdaringe** [comment]
```ts
// node_modules/.pnpm/parjs@0.16.1/node_modules/parjs/dist/lib/internal/combinators/then.js
                    else if (ps.isSoft) {
                        ps.kind = result_1.ResultKind.HardFail;
                        // if a i > 0 parser failed softly, this is a hard fail for us.
                        // also, propagate the internal expectation.
                        return;
                    }
```

This is the block. I'm not grokking this block promotes a soft failure to a hard failure. This block prevents my `maybe()` combinator. Any insight here?

**Comment by barona-mika-vilpas** [comment]
Hi!

I think you are correct that the `then` combinator is upgrading the soft failure to a hard failure here:
https://github.com/cdaringe/email-parser/blob/main/issue.ts#L41

This is also described here in the readme in more detail https://github.com/GregRos/parjs/#-hard-failure

However, I think fixing your issue is tricky due to a few things:
1. the parsers you have built parse leading whitespace
2. `onWSP_CRLF_mWSP` is not able to differentiate between these two cases:
    - leading whitespace + CRLF, followed by `1*WSP`
    - only `1*WSP`

Now, I'll try to offer some improvements:

1. You have 2 parsers that both start parsing whitespace. When a parser starts consuming input, it is assumed to be valid (this is exactly the case described in the readme). It may work better for you to parse _trailing_ whitespace instead. This way you can write parsers that have the same names as the tokens in your grammar: so instead of long names such as (example) `CRLF_mWSP` you can have a parser called `CRLF` which parses `CRLF + trailing whitespace`. As for the implementation, you can either bake the trailing whitespace parsing into each parser manually or have a function that returns a parser such as this (untested):

```ts
/** Parses the given parser followed by whitespace */
export function token<T>(parjser: p.Parjser<T>): p.Parjser<T> {
  return parjser
    .pipe(
      c.thenq(
        whitespace.pipe(
          c.many(),
          c.must(
            (ws) =>
              ws.length >= 1 || { reason: "at least 1 whitespace character" },
          ),
        ),
      ),
    )
    .expects(`The given token followed by whitespace`);
}

export const crlf = token(p.string("\r\n")).expects("crlf");
```

2. I think you can simplify your `atLeast` implementation to this

```ts
export const atLeast = (n: number, t: p.Parjser<string>) =>
  t.pipe(c.exactly<string>(n), flatString);
```

3. In general, it may be helpful to add `.expects("description of what this parser expects")` calls to your parsers. These will be helpful when looking at the stack traces.
4. In your tests you can have an assertion function that shows the stack traces when things fail. We don't have a good example of this yet so I just built this for you, you can try it out if you want:

```ts
/** An assertion that shows a nice stacktrace in case the parsing fails */
function assertParses<T>(
  result: ParjsResult<T>,
  expectedValue: T,
): asserts result is ParjsResult<T> {
  if (!result.isOk) {
    const error = result as ParjsFailure;
    throw new Error(
      `Expected success, got failure: ${error}\n${JSON.stringify(
        error,
        null,
        2,
      )}}`,
    );
  }

  // depending on your testing and assertion libraries, assert a condition
  expect(result.value).toEqual(expectedValue);
}
```

5. Some of your token parsers can be simplified by using built in parsers. Here is an example:
```ts
export const SP = p.space().expects("SP");
// instead of
export const SP = p
  .charCodeWhere((x) => (x === 0x20 ? true : failSoft("SP")));
```

6. I think your `atLeast` function may have a bug. Try this (untested):

```ts
export const atLeast = (n: number, t: p.Parjser<string>) =>
  t.pipe(c.exactly<string>(n), flatString);
```

**Comment by cdaringe** [comment]
Thanks for these great suggestions and advice! I will be picking up my project again shortly and will revisit with your guidance

**Comment by barona-mika-vilpas** [comment]
Closing this as it's been inactive for some weeks now. Feel free to reopen if needed.
