### ISSUE TITLE
Releasing a new version is having challenges

### ISSUE THREAD

**Issue by barona-mika-vilpas** [GregRos/parjs#95]
Here is a sample of the current issues:

https://github.com/GregRos/parjs/actions/runs/7531667407/job/20500724390

The goal with this issue is to release the next version (1.0.0)

**Comment by barona-mika-vilpas** [comment]
@GregRos sorry to bother you, but I think this may require you to perform some action.

Short situation update:
- I have added a bunch of features, fixed minor bugs and improved documentation. I am pretty comfortable with making a new release (details in the new [changelog](https://github.com/GregRos/parjs/blob/master/CHANGELOG.md))
- I see the CI build for publishing a new version fails due to missing npm credentials.

question: what's a good way to resolve this so that I could release new versions? How has this worked in the past?

I am not familiar with how this usually works at GitHub.

**Comment by barona-mika-vilpas** [comment]
@GregRos another request if you have the time:

I currently have access on this account (this is my work account), but it would simplify things a bit to get access for my personal account (@sp3ctum) as well. If you're pressed for time, this is not urgent.

**Comment by GregRos** [comment]
Hi! I'm back. The situation has changed from a waking nightmare to a lovecraftian monster that just sits outside and stares at me. I try to ignore it because there is nothing I can do. 

But it does mean I'm a lot more free to do stuff now.

# Thank you!
Thank you for all your work improving the library! I can see tons of improvements both in the code and in the organization. You've done awesome work.

I fixed the publish issue. I had used an older method to supply the credentials to the publish and when you changed it to yarn publish it stopped working. But I changed it according to the yarnrc docs and now it works.

I'll give access to the repo to your other user. No problem. :smile:

**Comment by sp3ctum** [comment]
Awesome, welcome back! Let's stare that monster down, or at least try.

I'm glad you like the changes 👍🏻 
I found working on the project helped me stare down some of my own monsters. I'm excited to have you and your ideas back; I think there are lots of cool things coming up this year.
